"use client";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import type { CourseEnrolment, CoursePage } from "@bpt-jersey/domain/courses";
import { CourseSessionGate, type CourseSession } from "../../../lib/courses/course-session";
import { courseApi, courseError } from "../../../lib/courses/course-client";
import { courseDate, courseMoney } from "../../../lib/courses/course-public-client";
import { useCourseNotices } from "../../../lib/courses/use-course-notices";
import "../../courses/courses.css";
const CourseEnrolForm=dynamic(()=>import("./course-enrol-form").then(m=>m.CourseEnrolForm),{loading:()=> <div className="course-loading">Loading enrolment form…</div>});
const CoursePaymentPanel=dynamic(()=>import("./course-payment-panel").then(m=>m.CoursePaymentPanel),{loading:()=> <div className="course-loading">Loading payment details…</div>});
function MyCourses({session}:{session:CourseSession}){
 const [page,setPage]=useState<CoursePage<CourseEnrolment>|null>(null);const [selected,setSelected]=useState<string|null>(null);const [courseId,setCourseId]=useState<string|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const {notices,read,cursor:noticeCursor,loadMore:moreNotices,busy:noticeBusy,error:noticeError}=useCourseNotices(session.uid);
 async function load(cursor?:string){setBusy(true);setError("");try{const p=await courseApi.enrolments({ownOnly:true,...(cursor?{cursor}:{})});setPage(old=>({...p,items:cursor?[...(old?.items??[]),...p.items]:p.items}));}catch(e){setError(courseError(e));}finally{setBusy(false);}}
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("course");if(id&&/^[0-9a-f-]{36}$/iu.test(id))setCourseId(id);void load();},[session.uid]);
 return <><div className="course-actions"><a href="/courses">Browse courses</a><a href="/account/courses/calendar">My course calendar and history</a><button className="course-link" disabled={busy} onClick={()=>void load()}>{busy?"Refreshing…":"Refresh my requests"}</button>{["owner","administrator"].includes(session.role)&&<a href="/admin/courses">Manage courses</a>}</div>{error&&<p className="course-error" role="alert">{error}</p>}{notices.filter(n=>!n.readAt).map(n=><aside className="course-notice" key={n.noticeId}><strong>{n.title}</strong><p>{n.message}</p><div className="course-actions">{n.enrolmentId&&<button className="course-link" onClick={()=>setSelected(n.enrolmentId)}>View enrolment</button>}<button className="course-link" onClick={()=>void read(n.noticeId).catch(e=>setError(courseError(e)))}>Mark as read</button></div></aside>)}{noticeError&&<p role="alert" className="course-error">{noticeError}</p>}{noticeCursor&&<button className="course-link" disabled={noticeBusy} onClick={()=>void moreNotices()}>Load earlier notices</button>}{courseId&&session.canApply&&<CourseEnrolForm key={courseId} courseId={courseId} onEnrolled={e=>{setCourseId(null);setSelected(e.enrolmentId);void load();}}/>}{!session.canApply&&<p className="course-notice">Your parent or guardian manages course enrolments and payments.</p>}{selected&&<CoursePaymentPanel key={selected} enrolmentId={selected} onChanged={()=>void load()} onClose={()=>setSelected(null)}/>}<h2>My enrolment requests</h2>{!page&&busy&&<div className="course-loading" role="status">Loading your courses…</div>}{page?.items.length===0&&<p>No course enrolments yet. Explore the catalogue to find your next programme.</p>}<ul className="course-list">{page?.items.map(e=><li className="course-row" key={e.enrolmentId}><div><strong>{e.reference||`Course request ${e.enrolmentId.slice(0,8)}`}</strong><p>{courseMoney(e.priceMinor)} · {e.status.replaceAll("_"," ")}</p><p className="course-meta">Requested {courseDate(e.createdAt)}</p></div><button className="course-button secondary" onClick={()=>setSelected(e.enrolmentId)}>View course and payment</button></li>)}</ul>{page?.cursor&&<button className="course-button secondary" disabled={busy} onClick={()=>void load(page.cursor!)}>Load more requests</button>}</>;
}
export default function AccountCoursesPage(){return <main className="course-page"><nav className="course-topnav" aria-label="Course navigation"><a href="/">BPT Jersey</a><a href="/courses">Course catalogue</a></nav><h1>My courses</h1><p className="course-intro">Keep track of your places, payments and course updates.</p><CourseSessionGate>{session=><MyCourses session={session}/>}</CourseSessionGate></main>;}
