"use client";
import { useCallback, useEffect, useState } from "react";
import type { MembershipApplication } from "@bpt-jersey/domain";
import { getIntroMembershipProofUrl, listIntroMembershipApplications, reviewIntroMembershipApplication } from "../../../lib/intro-conversion-client";
import { formatMoney } from "./billing-format";
export function IntroApplicationsPanel() {
  const [items,setItems]=useState<readonly MembershipApplication[]>([]); const [state,setState]=useState<"loading"|"ready"|"error">("loading"); const [reason,setReason]=useState<Record<string,string>>({}); const [links,setLinks]=useState<Record<string,string>>({}); const [busy,setBusy]=useState<string>(); const [failure,setFailure]=useState<string>();
  const load=useCallback(async()=>{setState("loading");try{setItems(await listIntroMembershipApplications());setState("ready");}catch{setState("error");}},[]); useEffect(()=>{void load();},[load]);
  async function evidence(id:string){setBusy(id);try{const result=await getIntroMembershipProofUrl(id);setLinks((current)=>({...current,[id]:result.url}));}finally{setBusy(undefined);}}
  async function decide(item:MembershipApplication, decision:"approve"|"needs_correction"|"reject"){if(decision==="approve"&&!window.confirm(item.billingPeriod==="per-session"?`Approve ${item.planName} (pay per class)?`:`Approve ${item.planName} and record ${formatMoney(item.priceMinor)} paid?`))return; const text=reason[item.applicationId]?.trim(); if(decision!=="approve"&&!text)return;setBusy(item.applicationId);setFailure(undefined);try{await reviewIntroMembershipApplication(decision==="approve"?{applicationId:item.applicationId,expectedRevision:item.revision,decision,occurredAt:new Date().toISOString()}:{applicationId:item.applicationId,expectedRevision:item.revision,decision,reason:text!});await load();}catch{setFailure(`${item.studentName ?? item.planName}: the decision was not saved. If the member has an open invoice or several subscriptions, resolve it in Billing first.`);}finally{setBusy(undefined);}}
  return <section className="admin-surface intro-applications" aria-labelledby="intro-applications-title"><div><p className="admin-eyebrow">From members</p><h2 id="intro-applications-title">Membership requests</h2></div>{state==="loading"?<p role="status">Loading applications...</p>:null}{state==="error"?<p role="status">Applications are unavailable.</p>:null}{failure?<p role="alert">{failure}</p>:null}{state==="ready"&&items.filter((item)=>item.status==="pending_review").length===0?<p>No membership requests are waiting.</p>:null}{items.filter((item)=>item.status==="pending_review").map((item)=><article key={item.applicationId} className="intro-application-row"><div><strong>{item.studentName ? `${item.studentName} · ${item.planName}` : item.planName}</strong><span>{item.conversionId===null?"Plan request from the account":"After the Intro Class"}</span><span>{item.site} · {formatMoney(item.priceMinor)} · {item.billingPeriod==="per-session"?"Pay as you go — no transfer":item.bankReference}</span></div><div className="intro-application-actions">{item.billingPeriod==="per-session"?null:links[item.applicationId]?<a href={links[item.applicationId]} target="_blank" rel="noreferrer">Open payment evidence</a>:<button type="button" disabled={busy===item.applicationId} onClick={()=>void evidence(item.applicationId)}>View evidence</button>}<label>Review reason<input value={reason[item.applicationId]??""} onChange={(event)=>setReason((current)=>({...current,[item.applicationId]:event.target.value}))}/></label><button type="button" onClick={()=>void decide(item,"approve")}>Approve</button><button type="button" onClick={()=>void decide(item,"needs_correction")}>Request correction</button><button type="button" onClick={()=>void decide(item,"reject")}>Reject</button></div></article>)}</section>;
}
