"use client";
import { useEffect, useRef, useState } from "react";
import type { CoursePage, PublicCourse } from "@bpt-jersey/domain/courses";
import { publicCourse, publicCourseSlots, courseDate, courseMoney, type PublicCourseSlot } from "../../../lib/courses/course-public-client";
export function CourseDetail() {
  const [course, setCourse] = useState<PublicCourse | null>(null); const [slots, setSlots] = useState<CoursePage<PublicCourseSlot> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const controller = useRef<AbortController | null>(null);
  useEffect(() => {const id = new URLSearchParams(window.location.search).get("course"); if (!id || !/^[0-9a-f-]{36}$/iu.test(id)) {setError("Choose a course from the catalogue."); return;} const next = new AbortController(); controller.current = next; void Promise.all([publicCourse(id, next.signal), publicCourseSlots(id, next.signal)]).then(([c,s]) => {setCourse(c); setSlots(s);}).catch(e => {if (!next.signal.aborted) setError((e as Error).message);}); return () => next.abort();}, []);
  async function more() {if (!course || !slots?.cursor || !controller.current) return; setBusy(true); try {const next = await publicCourseSlots(course.courseId, controller.current.signal, slots.cursor); setSlots({...next, items: [...slots.items, ...next.items]});} catch(e) {if (!controller.current.signal.aborted) setError((e as Error).message);} finally {setBusy(false);}}
  if (!course) return error ? <p className="course-error" role="alert">{error}</p> : <div className="course-loading" role="status">Loading course details…</div>;
  return <><h1>{course.title}</h1><p className="course-intro">{course.kind === "seminar" ? "Seminar" : "Weekly course"} with {course.instructorName}</p>{error && <p className="course-error" role="alert">{error}</p>}<div className="course-detail"><div><section><h2>What you’ll learn</h2><p className="course-prose">{course.description}</p><ul>{course.techniques.map((technique,i) => <li key={i}>{technique}</li>)}</ul></section><section><h2>Your session dates</h2><p>All times are in Jersey local time. Joining after the start covers the remaining dates at the full course price.</p><ol className="course-slots">{slots?.items.map(s => <li key={s.sessionId}><span><strong>Session {s.ordinal}</strong> · {courseDate(s.startAt)}–{new Date(s.endAt).toLocaleTimeString("en-GB",{timeZone:"Europe/Jersey",hour:"2-digit",minute:"2-digit"})}</span><span>{s.status === "cancelled" ? "Cancelled" : s.startAt <= new Date().toISOString() ? "Started / finished" : "Upcoming"}</span></li>)}</ol>{slots?.cursor && <button className="course-button secondary" disabled={busy} onClick={() => void more()}>Load more dates</button>}</section><section><h2>Cancellation terms</h2><p className="course-prose">{course.cancellationTerms}</p></section></div><aside className="course-summary"><p className="course-price">{courseMoney(course.priceMinor)}</p><p>One payment for this course</p><dl className="course-facts"><div><dt>Sessions</dt><dd>{course.sessionCount}</dd></div><div><dt>Ages</dt><dd>{course.minAge}{course.maxAge === null ? "+" : `–${course.maxAge}`}</dd></div><div><dt>Location</dt><dd>{course.locationName}</dd></div><div><dt>Coach</dt><dd>{course.instructorName}</dd></div></dl>{course.availability !== "closed" ? <a className="course-button" href={`/account/courses?course=${course.courseId}`}>{course.availability === "waitlist" ? "Join the waitlist" : "Enrol in this course"}</a> : <p className="course-notice">Enrolment is closed.</p>}<p className="course-meta">{course.availability === "waitlist" ? "No payment is needed while you wait for a place." : "Reserve a place, transfer the payment and upload your reference and screenshot for office approval."}</p></aside></div></>;
}
