"use client";
import { useEffect, useRef, useState } from "react";
import type { CoursePage, PublicCourse } from "@bpt-jersey/domain/courses";
import { publicCourses, courseDate, courseMoney } from "../../lib/courses/course-public-client";
export function CourseCatalogue() {
  const [page, setPage] = useState<CoursePage<PublicCourse> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const controller = useRef<AbortController | null>(null);
  async function load(cursor?: string) {controller.current?.abort(); const next = new AbortController(); controller.current = next; setBusy(true); setError(""); try {const value = await publicCourses(next.signal, cursor); if (!next.signal.aborted) setPage(old => ({...value, items: cursor ? [...(old?.items ?? []), ...value.items] : value.items}));} catch(e) {if (!next.signal.aborted) setError((e as Error).message);} finally {if (!next.signal.aborted) setBusy(false);}}
  useEffect(() => {void load(); return () => controller.current?.abort();}, []);
  return <section aria-label="Course catalogue">{error && <div className="course-error" role="alert">{error} <button className="course-link" onClick={() => void load()}>Try again</button></div>}{!page && busy && <div className="course-loading" role="status">Loading upcoming courses…</div>}{page?.items.length === 0 && <div className="course-panel"><h2>New courses are on the way</h2><p>Check back for the next programme or <a href="/#contact">contact the academy</a>.</p></div>}<ul className="course-list">{page?.items.map(c => <li className="course-row" key={c.courseId}><div><p className="course-meta">{c.kind === "seminar" ? "Seminar" : "Weekly course"} · Ages {c.minAge}{c.maxAge === null ? "+" : `–${c.maxAge}`}</p><h2><a href={`/courses/view?course=${c.courseId}`}>{c.title}</a></h2><p>{c.instructorName} · {c.locationName}</p><p className="course-meta">{c.nextSessionAt ? `Next session: ${courseDate(c.nextSessionAt)}` : "Enrolment closed"} · {c.sessionCount} sessions in total</p></div><div><p className="course-price">{courseMoney(c.priceMinor)}</p><p className="course-meta">One payment</p><a className="course-button secondary" href={`/courses/view?course=${c.courseId}`}>{c.availability === "waitlist" ? "View waitlist details" : "View course"}</a></div></li>)}</ul>{page?.cursor && <button className="course-button secondary" disabled={busy} onClick={() => void load(page.cursor!)}>{busy ? "Loading…" : "Load more courses"}</button>}</section>;
}
