"use client";
import { useState, type FormEvent } from "react";
import type { AdminSession } from "../../../lib/admin-auth";
import { createStaffWithPassword } from "../../../lib/team-access-client";
export function DirectStaffForm({ session, onCreated }: { session: AdminSession; onCreated: () => void }) {
  const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [role,setRole]=useState<"coach"|"administrator"|"owner">("coach");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{await createStaffWithPassword({displayName:name.trim(),email:email.trim().toLowerCase(),password,role});setName("");setEmail("");setPassword("");setMessage("Staff account created. They must change the initial password or link Google at first sign-in.");onCreated();}catch{setMessage("The staff account could not be created. Check that the email is not already used.");}finally{setBusy(false);}}
  return <form className="staff-card" onSubmit={(event)=>void submit(event)}><p className="admin-eyebrow">Direct credentials</p><h3>Create staff with initial password</h3><p className="staff-hint">For coaches and assistants choose Coach / assistant. Office roles can only be created by an owner. The initial password must be replaced, or the person can link Google.</p><div className="staff-form-grid"><label className="staff-field">Full name<input value={name} onChange={(e)=>setName(e.target.value)} minLength={2} maxLength={160} required /></label><label className="staff-field">Direct staff email<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required /></label><label className="staff-field">Initial password<input type="password" autoComplete="new-password" value={password} onChange={(e)=>setPassword(e.target.value)} minLength={12} maxLength={128} required /></label><label className="staff-field">Direct staff role<select value={role} onChange={(e)=>setRole(e.target.value as typeof role)}><option value="coach">Coach / assistant</option>{session.role==="owner"?<><option value="administrator">Office administrator</option><option value="owner">Owner</option></>:null}</select></label></div><button className="staff-primary-button" disabled={busy} type="submit">{busy?"Creating...":"Create staff account"}</button>{message?<p role="status" className="staff-message">{message}</p>:null}</form>;
}
