"use client";
import { useState, type FormEvent } from "react";
import type { AdminSession } from "../../../lib/admin-auth";
import { createStaffWithPassword } from "../../../lib/team-access-client";
import { coachBelts, coachBeltLabels, type CoachBelt } from "@bpt-jersey/domain/staff/team-access";
export function DirectStaffForm({ session, onCreated }: { session: AdminSession; onCreated: () => void }) {
  const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [role,setRole]=useState<"coach"|"administrator"|"owner">("coach");const [belt,setBelt]=useState<CoachBelt|"">("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{await createStaffWithPassword({displayName:name.trim(),email:email.trim().toLowerCase(),password,role,...(role==="coach"&&belt?{belt}:{})});setName("");setEmail("");setBelt("");setMessage("Staff account created. They must change the initial password or link Google at first sign-in.");onCreated();}catch{setMessage("The staff account could not be created. Check that the email is not already used and that the password does not contain it.");}finally{setPassword("");setBusy(false);}}
  return <form className="staff-card" onSubmit={(event)=>void submit(event)}><p className="admin-eyebrow">Direct credentials</p><h3>Create staff with initial password</h3><p className="staff-hint">This is the only way to create staff. For coaches and assistants choose Coach / assistant. A member who becomes a coach gets a separate staff account: their name can match their member record, but use an email different from their member login. Office roles can only be created by an owner. The initial password must be replaced, or the person can link Google.</p><div className="staff-form-grid"><label className="staff-field">Full name<input value={name} onChange={(e)=>setName(e.target.value)} minLength={2} maxLength={160} required /></label><label className="staff-field">Direct staff email<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required /></label><label className="staff-field">Initial password<input type="password" autoComplete="new-password" value={password} onChange={(e)=>setPassword(e.target.value)} minLength={12} maxLength={128} required /></label><label className="staff-field">Direct staff role<select value={role} onChange={(e)=>setRole(e.target.value as typeof role)}><option value="coach">Coach / assistant</option>{session.role==="owner"?<><option value="administrator">Office administrator</option><option value="owner">Owner</option></>:null}</select></label>{role==="coach"?<label className="staff-field">Belt shown on the website<select value={belt} onChange={(e)=>setBelt(e.target.value as CoachBelt)} required><option value="" disabled>Choose a belt</option>{coachBelts.map((value)=><option key={value} value={value}>{coachBeltLabels[value]}</option>)}</select></label>:null}</div><button className="staff-primary-button" disabled={busy} type="submit">{busy?"Creating...":"Create staff account"}</button>{message?<p role="status" className="staff-message">{message}</p>:null}</form>;
}
